Fix promisify for node 12
{
    "errorType": "TypeError",
    "errorMessage": "promisify is not a function",
    "stack": [
        "TypeError: promisify is not a function",
        "    at Object.<anonymous> (/var/task/src/util/generateRSAKeyPair.js:8:25)",
        "    at Module._compile (internal/modules/cjs/loader.js:955:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)",
        "    at Module.load (internal/modules/cjs/loader.js:811:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:723:14)",
        "    at Module.require (internal/modules/cjs/loader.js:848:19)",
        "    at require (internal/modules/cjs/helpers.js:74:18)",
        "    at Object.<anonymous> (/var/task/src/acme/register/createAccount.js:1:28)",
        "    at Module._compile (internal/modules/cjs/loader.js:955:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)"
    ]
}